# Generated by Django 6.0 on 2025-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationsubmission',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userallocation',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='allocationsubmission',
            index=models.Index(fields=['user_id', '-submitted_at'], name='allocator_a_user_id_4968f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userallocation',
            index=models.Index(fields=['user_id', 'created_at'], name='allocator_u_user_id_e7c22c_idx'),
        ),
    ]
