# Generated by Django 6.0 on 2025-12-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0002_allocationsubmission_user_id_userallocation_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAggregate',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aggregate', serialize=False, to='allocator.budgetcategory')),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all percentages for this category', max_digits=15)),
                ('submission_count', models.BigIntegerField(default=0, help_text='Number of submissions for this category')),
                ('avg_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Calculated average: total_percentage / submission_count', max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Category Aggregate',
                'verbose_name_plural': 'Category Aggregates',
                'ordering': ['category__display_order'],
            },
        ),
    ]
